name: Backend
on:
    - push
    - pull_request
    - workflow_dispatch

jobs:
    testing:
        name: Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.21'
            - name: Go Test
              run: |
                cd ./backend/src
                go test