name: Backend
on:
    - push
    - pull_request
    - workflow_dispatch

jobs:
    testing:
        name: Testing
        runs-on: ubuntu-latest
        services:
          db:
            image: mariadb:latest
            ports:
              - 3306:3306
            env:
              MARIADB_ROOT_PASSWORD: root
              MARIADB_DATABASE: com668
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.21'
            - name: Go Test
              env:
                DB_HOST: 127.0.0.1:3306
                DB_USER: root
                DB_PASS: root
                DB_NAME: com668
              run: |
                cd ./backend/src/test
                go test -v -coverpkg com668-backend/... -covermode set