name: Frontend

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Install Deno
            uses: denoland/setup-deno@v1
            with:
                deno-version: stable
    linting:
        name: Linting
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - run: deno task lint
    testing:
        name: Testing
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - run: deno task test