name: Frontend

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.18'
            - name: Install PNPM
              run: npm i -g pnpm
            - name: Install App Dependencies
              run: |
                cd ./frontend
                pnpm i
            - name: Next Lint
              run: |
                cd ./frontend
                pnpm run lint
    testing:
        name: Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.18'
            - name: Install PNPM
              run: npm i -g pnpm
            - name: Install App Dependencies
              run: |
                cd ./frontend
                pnpm i
            - name: Test
              run: |
                cd ./frontend
                pnpm run test