name: Frontend

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Deno
              uses: denoland/setup-deno@v1
              with:
                deno-version: 1.46.3
            - name: Deno Lint
              run: |
                cd ./frontend
                deno task lint
    testing:
        name: Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Deno
              uses: denoland/setup-deno@v1
              with:
                deno-version: 1.46.3
            - name: Deno Test
              run: |
                cd ./frontend
                deno task test