name: Processor
on:
    - push
    - pull_request
    - workflow_dispatch

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.9'
          - name: Install Dev Dependencies
            run: |
              cd ./processor
              python3 -m pip install -r requirements-dev.txt
          - name: Flake8 Linting
            run: |
              cd ./processor/src
              flake8 --config ../bin/flake8.cfg
    testing:
        name: Testing
        runs-on: ubuntu-latest
        env:
              ENV: dev
              API_HOST: https://example.com
              API_USER_EMAIL: test@example.com
              API_USER_PW: password
              SENTRY_TOKEN: sntryu_1234567890
              SLACK_TOKEN: xoxb-1234567890-1234567890123-123456789012345678901234
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Setup Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.9'
          - name: Install Dependencies
            run: |
              cd ./processor
              pip3 install -r requirements.txt
              pip3 install -r requirements-dev.txt
              pip3 install -e .
          - name: Pytest Testing
            run: |
              cd ./processor/src/test
              pytest --disable-warnings -v --cov-config=../../bin/.coveragerc