name: Processor
on:
    - push
    - pull_request
    - workflow_dispatch

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
    linting:
        name: Linting
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Install Dev Dependencies
              run: |
                cd ./processor
                python3 -m pip install -r requirements-dev.txt
            - name: Linting
              run: flake8 --config ./bin/flake8.cfg
    testing:
        name: Testing
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Install Dependencies
              run: |
                cd ./processor
                python3 -m pip install -r requirements.txt
                python3 -m pip install -r requirements-dev.txt
            - name: Testing
              run: pytest --disable-warnings -v